runtime: nodejs16

env: standard
service: my-application
entrypoint: npm run migrate && npm start

env_variables:
  DATABASE_URL: "postgresql://user:fahad@35.192.15.151:5432/slash"
  TOKEN_KEY: "fahaduse-secret-key"
  AWS_S3_ACCESS_KEY_ID: AKIAYXZSIY2URAJGPL7G
  AWS_S3_SECRET_ACCESS_KEY: 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
  BUCKET_NAME: horsefly-bucket